import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import MyToastContainer from "./components/taoster";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={inter.className + ' h-[100vh] bg-white'}>
        <Navbar>
          {children}
        </Navbar>
        <MyToastContainer />
        {/* <Footer /> */}
      </body>
    </html>
  );
}
